#!/bin/bash

DIST_DIR=./dist
OFFLINE_DIR=$DIST_DIR/offline

download_node() {
    cd $OFFLINE_DIR
    node_version=$(curl --silent --get https://semver.io/node/resolve/0.10.x)
    NODE_INSTALLER=node-installer.tar.gz
    NODE_URL="http://s3pository.heroku.com/node/v$node_version/node-v$node_version-linux-x64.tar.gz"
    curl $NODE_URL > $NODE_INSTALLER
}

download_meteor_tarball() {
    release=$1
    platform=$2
    INSTALL_TMPDIR=$OFFLINE_DIR/.meteor-install-tmp
    cd $OFFLINE_DIR
    mkdir $INSTALL_TMPDIR
    TARBALL_URL="https://d3sqy0vbqsdhku.cloudfront.net/packages-bootstrap/${release}/meteor-bootstrap-${platform}.tar.gz"
    curl --progress-bar --fail "$TARBALL_URL" | tar -xzf - -C "$INSTALL_TMPDIR" -o
}

download_meteor() {
    cd $OFFLINE_DIR
    METEOR_INSTALL_SCRIPT=install_meteor.sh
    curl https://install.meteor.com/ > $METEOR_INSTALL_SCRIPT

    METEOR_VERSION=1.2.1
    download_meteor_tarball $METEOR_VERSION "os.osx.x86_64"
    download_meteor_tarball $METEOR_VERSION "os.linux.x86_32"
    download_meteor_tarball $METEOR_VERSION "os.linux.x86_64"
}

package() {
    tar zcf dist.tar.gz dist
}

rm -rf $DIST_DIR
mkdir -p $OFFLINE_DIR
cp -r bin $DIST_DIR
download_node
download_meteor
package